# -*- coding: utf-8 -*-
"""00TensorFlowFundamental.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16YXKK4F0go0fqTFJ8Gv56xO8x9cv___Z
"""

import tensorflow as tf
print(tf.__version__)

scalar = tf.constant(7)

scalar

scalar.ndim

vector = tf.constant([10, 10])

vector

vector.ndim

matrix = tf.constant([[10, 3],
                     [29, 40]])

matrix

matrix.ndim

another_matrix = tf.constant([[10, 2],
                              [3., 2.]], dtype=tf.float32)

another_matrix

t = tf.constant([[[10]]])

t

import fxcmpy

import tensorflow as tf
t1 = tf.constant(7, dtype=tf.float32)

t1

t2 = tf.Variable(20., dtype=tf.float16)

t2

t3 =  tf.Variable([9, 8], dtype=tf.float32)

t1

t2.assign(10)

t3[0]

t3[0].assign(10)

t3[0]

random1 = tf.random.Generator.from_seed(42)

random1

random1.normal(shape=(3, 2))

random1.uniform(shape=(3, 2))

import tensorflow as tf

not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [6, 7]])

not_shuffled

tf.random.shuffle(not_shuffled)

tf.random.shuffle(not_shuffled)

tf.random.shuffle(not_shuffled, seed=42)

tf.random.shuffle(not_shuffled, seed=42)

tf.random.shuffle(not_shuffled, seed=42)

tf.random.shuffle(not_shuffled, seed=42)

tf.random.shuffle(not_shuffled, seed=42)

tf.random.shuffle(not_shuffled, seed=42)

tf.random.shuffle(not_shuffled, seed=42)

tf.random.set_seed(42)

tf.random.shuffle(not_shuffled)

tf.random.shuffle(not_shuffled)

tf.random.shuffle(not_shuffled)

import tensorflow as tf

v1 = tf.Variable(10.0, dtype=tf.float32)

v1

t3 =  tf.Variable(8, dtype=tf.float32)

v1.assign(10)

import numpy as np

ones = np.ones(10)

ones

one_tensor = tf.constant(ones)

one_tensor

one_new_shape = tf.constant(ones, shape=(5, 2))
one_new_shape

rank_4_rensorn = tf.zeros(shape=[10, 2])

rank_4_rensorn

